# See https://symfony.com/doc/current/email/dev_environment.html

swiftmailer:
    transport:        gmail
    username:
    password:
    host:             smtp.gmail.com
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
